nomes_paises_pt = {
    "Afeganistão": "Afghanistan",
    "Albânia": "Albania",
    "Argélia": "Algeria",
    "Samoa Americana": "American Samoa",
    "Andorra": "Andorra",
    "Angola": "Angola",
    "Antígua e Barbuda": "Antigua and Barbuda",
    "Argentina": "Argentina",
    "Armênia": "Armenia",
    "Aruba": "Aruba",
    "Austrália": "Australia",
    "Áustria": "Austria",
    "Azerbaijão": "Azerbaijan",
    "Bahamas": "Bahamas, The",
    "Bahrein": "Bahrain",
    "Bangladesh": "Bangladesh",
    "Barbados": "Barbados",
    "Bielorrússia": "Belarus",
    "Bélgica": "Belgium",
    "Belize": "Belize",
    "Benim": "Benin",
    "Bermudas": "Bermuda",
    "Butão": "Bhutan",
    "Bolívia": "Bolivia",
    "Bósnia e Herzegovina": "Bosnia and Herzegovina",
    "Botsuana": "Botswana",
    "Brasil": "Brazil",
    "Ilhas Virgens Britânicas": "British Virgin Islands",
    "Brunei": "Brunei Darussalam",
    "Bulgária": "Bulgaria",
    "Burkina Faso": "Burkina Faso",
    "Burundi": "Burundi",
    "Cabo Verde": "Cabo Verde",
    "Camboja": "Cambodia",
    "Camarões": "Cameroon",
    "Canadá": "Canada",
    "Ilhas Cayman": "Cayman Islands",
    "República Centro-Africana": "Central African Republic",
    "Chade": "Chad",
    "Ilhas do Canal": "Channel Islands",
    "Chile": "Chile",
    "China": "China",
    "Colômbia": "Colombia",
    "Comores": "Comoros",
    "República Democrática do Congo": "Congo, Dem. Rep.",
    "República do Congo": "Congo, Rep.",
    "Costa Rica": "Costa Rica",
    "Costa do Marfim": "Cote d'Ivoire",
    "Croácia": "Croatia",
    "Cuba": "Cuba",
    "Curaçao": "Curacao",
    "Chipre": "Cyprus",
    "Tchéquia": "Czechia",
    "Dinamarca": "Denmark",
    "Djibuti": "Djibouti",
    "Dominica": "Dominica",
    "República Dominicana": "Dominican Republic",
    "Equador": "Ecuador",
    "Egito": "Egypt, Arab Rep.",
    "El Salvador": "El Salvador",
    "Guiné Equatorial": "Equatorial Guinea",
    "Eritreia": "Eritrea",
    "Estônia": "Estonia",
    "Essuatíni": "Eswatini",
    "Etiópia": "Ethiopia",
    "Ilhas Faroé": "Faroe Islands",
    "Fiji": "Fiji",
    "Finlândia": "Finland",
    "França": "France",
    "Polinésia Francesa": "French Polynesia",
    "Gabão": "Gabon",
    "Gâmbia": "Gambia, The",
    "Geórgia": "Georgia",
    "Alemanha": "Germany",
    "Gana": "Ghana",
    "Gibraltar": "Gibraltar",
    "Grécia": "Greece",
    "Groenlândia": "Greenland",
    "Granada": "Grenada",
    "Guam": "Guam",
    "Guatemala": "Guatemala",
    "Guiné": "Guinea",
    "Guiné-Bissau": "Guinea-Bissau",
    "Guiana": "Guyana",
    "Haiti": "Haiti",
    "Honduras": "Honduras",
    "Hong Kong (RAE da China)": "Hong Kong SAR, China",
    "Hungria": "Hungary",
    "Islândia": "Iceland",
    "Índia": "India",
    "Indonésia": "Indonesia",
    "Irã": "Iran, Islamic Rep.",
    "Iraque": "Iraq",
    "Irlanda": "Ireland",
    "Ilha de Man": "Isle of Man",
    "Israel": "Israel",
    "Itália": "Italy",
    "Jamaica": "Jamaica",
    "Japão": "Japan",
    "Jordânia": "Jordan",
    "Cazaquistão": "Kazakhstan",
    "Quênia": "Kenya",
    "Quiribáti": "Kiribati",
    "Coreia do Norte": "Korea, Dem. People's Rep.",
    "Coreia do Sul": "Korea, Rep.",
    "Kosovo": "Kosovo",
    "Kuwait": "Kuwait",
    "Quirguistão": "Kyrgyz Republic",
    "Laos": "Lao PDR",
    "Letônia": "Latvia",
    "Líbano": "Lebanon",
    "Lesoto": "Lesotho",
    "Libéria": "Liberia",
    "Líbia": "Libya",
    "Liechtenstein": "Liechtenstein",
    "Lituânia": "Lithuania",
    "Luxemburgo": "Luxembourg",
    "Macau (RAE da China)": "Macao SAR, China",
    "Madagascar": "Madagascar",
    "Malawi": "Malawi",
    "Malásia": "Malaysia",
    "Maldivas": "Maldives",
    "Mali": "Mali",
    "Malta": "Malta",
    "Ilhas Marshall": "Marshall Islands",
    "Mauritânia": "Mauritania",
    "Maurício": "Mauritius",
    "México": "Mexico",
    "Micronésia, Estados Federados": "Micronesia, Fed. Sts.",
    "Moldávia": "Moldova",
    "Mônaco": "Monaco",
    "Mongólia": "Mongolia",
    "Montenegro": "Montenegro",
    "Marrocos": "Morocco",
    "Moçambique": "Mozambique",
    "Mianmar": "Myanmar",
    "Namíbia": "Namibia",
    "Nauru": "Nauru",
    "Nepal": "Nepal",
    "Países Baixos": "Netherlands",
    "Nova Caledônia": "New Caledonia",
    "Nova Zelândia": "New Zealand",
    "Nicarágua": "Nicaragua",
    "Níger": "Niger",
    "Nigéria": "Nigeria",
    "Macedônia do Norte": "North Macedonia",
    "Ilhas Marianas do Norte": "Northern Mariana Islands",
    "Noruega": "Norway",
    "Omã": "Oman",
    "Paquistão": "Pakistan",
    "Palau": "Palau",
    "Panamá": "Panama",
    "Papua-Nova Guiné": "Papua New Guinea",
    "Paraguai": "Paraguay",
    "Peru": "Peru",
    "Filipinas": "Philippines",
    "Polônia": "Poland",
    "Portugal": "Portugal",
    "Porto Rico (EUA)": "Puerto Rico (US)",
    "Catar": "Qatar",
    "Romênia": "Romania",
    "Rússia": "Russian Federation",
    "Ruanda": "Rwanda",
    "Samoa": "Samoa",
    "San Marino": "San Marino",
    "São Tomé e Príncipe": "Sao Tome and Principe",
    "Arábia Saudita": "Saudi Arabia",
    "Senegal": "Senegal",
    "Sérvia": "Serbia",
    "Seicheles": "Seychelles",
    "Serra Leoa": "Sierra Leone",
    "Singapura": "Singapore",
    "São Martinho (parte holandesa)": "Sint Maarten (Dutch part)",
    "Eslováquia": "Slovak Republic",
    "Eslovênia": "Slovenia",
    "Ilhas Salomão": "Solomon Islands",
    "Somália": "Somalia, Fed. Rep.",
    "África do Sul": "South Africa",
    "Sudão do Sul": "South Sudan",
    "Espanha": "Spain",
    "Sri Lanka": "Sri Lanka",
    "São Cristóvão e Névis": "St. Kitts and Nevis",
    "Santa Lúcia": "St. Lucia",
    "São Martinho (parte francesa)": "St. Martin (French part)",
    "São Vicente e Granadinas": "St. Vincent and the Grenadines",
    "Sudão": "Sudan",
    "Suriname": "Suriname",
    "Suécia": "Sweden",
    "Suíça": "Switzerland",
    "Síria": "Syrian Arab Republic",
    "Tajiquistão": "Tajikistan",
    "Tanzânia": "Tanzania",
    "Tailândia": "Thailand",
    "Timor-Leste": "Timor-Leste",
    "Togo": "Togo",
    "Tonga": "Tonga",
    "Trinidad e Tobago": "Trinidad and Tobago",
    "Tunísia": "Tunisia",
    "Turquia": "Turkiye",
    "Turcomenistão": "Turkmenistan",
    "Ilhas Turks e Caicos": "Turks and Caicos Islands",
    "Tuvalu": "Tuvalu",
    "Uganda": "Uganda",
    "Ucrânia": "Ukraine",
    "Emirados Árabes Unidos": "United Arab Emirates",
    "Reino Unido": "United Kingdom",
    "Estados Unidos": "United States",
    "Uruguai": "Uruguay",
    "Uzbequistão": "Uzbekistan",
    "Vanuatu": "Vanuatu",
    "Venezuela": "Venezuela, RB",
    "Vietnã": "Viet Nam",
    "Ilhas Virgens Americanas": "Virgin Islands (U.S.)",
    "Cisjordânia e Faixa de Gaza": "West Bank and Gaza",
    "Iêmen": "Yemen, Rep.",
    "Zâmbia": "Zambia",
    "Zimbábue": "Zimbabwe",
}
